title: <a href="https://www.christiansatzky.com" target="_blank">Christian Satzky</a>
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Projects by Christian Satzky — Empirical asset pricing, factor investing, and estimation of market risk.
  
theme: jekyll-theme-minimal
google_analytics: G-F63Q8SHJ31
