title: <a href="https://www.linkedin.com/in/christian-satzky/" target="_blank">Christian Satzky</a>
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Statistical Programmer
  <br><br>
  Certified FRM
  <br><br>
  UniCredit CIB Markets
  <br><br>
  <a href="https://www.linkedin.com/in/christian-satzky/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-F63Q8SHJ31
